version: '2'
services:
  web:
    build: .
    ports:
    - "80:80"
    volumes:
    - logvolume01:/var/log
    - codevolume01:/var/www/html
    links:
    - mysql
  mysql:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
volumes:
  logvolume01: {}
  codevolume01: {}
